### ISSUE TITLE
Should we not require source document if there is no policy and unknown? or just unknown

### ISSUE THREAD

**Issue by eclee25** [HopkinsIDD/covid19-interventions#18]
@scottyaz 
If the policy changes from required to no policy, we probably want source docs
If the policy is no policy at the first report, we probably can't find source docs...

Maybe need to rethink phrasing?

**Comment by fjones2222** [comment]
I think I have covered this for most sections, but worth double checking

**Comment by scottyaz** [comment]
This also applies to the required dates. Makes me think we should not require initial entry until there is a policy in place. @eclee25 what do you think? This would mean we could probably get rid of unknowns but also want a clever way to document that there is no update.
