### ISSUE TITLE
admin 1 unit not working

### ISSUE THREAD

**Issue by fjones2222** [HopkinsIDD/covid19-interventions#20]
I tried to enter an example for an admin 1 unit and could not find Maryland, USA or Pwani, Tanzania. Looks like there are only a few options for this geographic level

**Comment by salauer** [comment]
Also, the adm1 unit should be subset after the country is chosen. Even after I click on the country, the full list of adm1 units is displayed.

**Comment by scottyaz** [comment]
Yeah - we are working on a solution Redcap doesn't allow for this.

**Comment by fjones2222** [comment]
New format addresses this issue
