### ISSUE TITLE
Branching logic error for Restaurants

### ISSUE THREAD

**Issue by fjones2222** [HopkinsIDD/covid19-interventions#28]
Some how this showed up underneath Restaurants “Have there been changes to closure policy for leisure and entertainment venues?”

**Comment by sarahleavitt** [comment]
This is still here in the new format under the "Restaurant Closures" survey. I wonder if this question should be under the logic of "partially closed"

**Comment by fjones2222** [comment]
I do not see the issue here any more, but maybe I am missing it. Happy to reopen if I am missing something
