### ISSUE TITLE
Difficult to find correct administrative 1 unit

### ISSUE THREAD

**Issue by sarahleavitt** [HopkinsIDD/covid19-interventions#34]
Is there a way to subset to the Administrative 1 units that match the country selected? It is difficult to find the desired state/province because the list is so long. Alternatively, the list could be sorted alphabetically. Additionally, there could be some names (like "Northeast" etc.) which could apply to multiple countries.

**Comment by scottyaz** [comment]
It is now filtering correctly (a bit of a hack how we had to do it but...)
