### ISSUE TITLE
Forced to upload multiple documents

### ISSUE THREAD

**Issue by sarahleavitt** [HopkinsIDD/covid19-interventions#38]
For questions like symptom screening by land/sea/air/borders and travel by land/sea/air, currently you have to submit individual documents for each of the travel types. This is likely unnecessary as this information is likely coming from one source. Is there a way to allow for uploading multiple documents? Then you could only ask for the document once and allow for multiple in the rare case it is necessary. That would make answering these questions much easier.

**Comment by sarahleavitt** [comment]
Also relevant for school closures.

**Comment by sarahleavitt** [comment]
And contact tracing

**Comment by fjones2222** [comment]
just change this for school closures

**Comment by fjones2222** [comment]
just changed for symptom screening

**Comment by fjones2222** [comment]
Changed for borders

**Comment by fjones2222** [comment]
And Contact tracing

**Comment by fjones2222** [comment]
Basically I have made it so that each section you update, you only upload one document at the end. It means that we will expect people to upload a zipped file if multiple docs are necessary.
