### ISSUE TITLE
Would it help to add recommended/required to household confinement

### ISSUE THREAD

**Issue by sarahleavitt** [HopkinsIDD/covid19-interventions#45]
This is one area where it might make sense to ask for more information (optionally probably) about whether the recommendations were required or recommended. Perhaps also capturing if it is like what some states are doing - saying stay home but no police and you can still go on walks verses what happened in China and is happening now in Italy which are much more restrictive and enforced lockdowns.

**Comment by scottyaz** [comment]
Yes - Updated this field to capture more details including required/reccomended.
