### ISSUE TITLE
Linking geographies with same or similar enough policies

### ISSUE THREAD

**Issue by kararudolph** [HopkinsIDD/covid19-interventions#48]
It would be great to have a way to link administrative units who have the same/similar enough policy. Like if Michigan’s policy is based on CA’s, it would be nice to be able to indicate that. Some up-front work but would probably be helpful down the road in analyzing.

**Comment by fjones2222** [comment]
I think this is going to be challenging to think how to implement in a survey systematically and would probably have to be done in the details section. Feel free to reopen this issue if you have any suggestions.
