### ISSUE TITLE
 Admin 1 Unit and Updates

### ISSUE THREAD

**Issue by kararudolph** [HopkinsIDD/covid19-interventions#49]
The "lowest level administrative division name" is not clear to me. If I want to report on NY state, would I leave this blank? If I wanted to report on NYC, would I put City? But then there is nowhere to put which city…
<img width="776" alt="Screen Shot 2020-03-25 at 11 52 52 AM" src="https://user-images.githubusercontent.com/5614175/77557471-2dbe1780-6e90-11ea-965d-3b78308a17bd.png">

**Comment by scottyaz** [comment]
This is the field where you are supposed to put the city name not the type of admin unit. 

Is this any clearer:
![image](https://user-images.githubusercontent.com/67367/77579153-1efc5280-6eda-11ea-83bb-7c63c5b91807.png)

**Comment by kararudolph** [comment]
yes!
