### ISSUE TITLE
add option to testing symptomatic individuals

### ISSUE THREAD

**Issue by kararudolph** [HopkinsIDD/covid19-interventions#54]
Item 188: testing only upon hospitalization should be added as an option
<img width="928" alt="Screen Shot 2020-03-25 at 1 37 48 PM" src="https://user-images.githubusercontent.com/5614175/77567485-995ab180-6e9d-11ea-9673-2becbb588a31.png">

**Comment by fjones2222** [comment]
@kararudolph @scottyaz  does symptom severity cover hospitalization already?

**Comment by kararudolph** [comment]
in NYC, for example, it was based on fever (i.e., symptom severity?) but then the condition was added that only people who were severe enough to be admitted on the spot could be tested. This is also "symptom severity", but I wondered if it merited its own category since it is very different from fever.

**Comment by fjones2222** [comment]
added hospitalization
