### ISSUE TITLE
restaurant capacity

### ISSUE THREAD

**Issue by kararudolph** [HopkinsIDD/covid19-interventions#55]
This should probably be % of capacity and not an integer, right?
<img width="838" alt="Screen Shot 2020-03-25 at 1 31 22 PM" src="https://user-images.githubusercontent.com/5614175/77567821-18e88080-6e9e-11ea-879e-394d982ec55f.png">

**Comment by fjones2222** [comment]
@kararudolph I made this question no longer required. If the policy is not % of capacity hopefull folks would put in details? Thoughts?

**Comment by scottyaz** [comment]
At least here in switzerland it is either based on density or a specific max number of people. i am made it only restricted to be numeric now and asked user to clarify units in details section. This might be one of those fields that will not be useful in the end....
