### ISSUE TITLE
school closures clarification

### ISSUE THREAD

**Issue by kararudolph** [HopkinsIDD/covid19-interventions#56]
How would one classify universal school closures except for programs that are provided to care for children of essential personnel (like healthcare workers)?

**Comment by scottyaz** [comment]
I think that one will be lost in the details free text forever and ever. Do you think that is something we should be capturing or just clarify what to do in this situation @kararudolph ?

**Comment by scottyaz** [comment]
I think this should be required and added this caveat to the guidance document/SOP
