### ISSUE TITLE
Clarification between limiting movement v. household confinement

### ISSUE THREAD

**Issue by kararudolph** [HopkinsIDD/covid19-interventions#57]
Limiting movement: Can you give some examples of common policies? Or check boxes for common policies? 
e..g, only going outside for necessities, or to work if essential personnel?
How does one differentiate between limiting movement and household confinement?
<img width="844" alt="Screen Shot 2020-03-25 at 12 32 34 PM" src="https://user-images.githubusercontent.com/5614175/77568104-84cae900-6e9e-11ea-815e-e84b5813c088.png">

**Comment by scottyaz** [comment]
limited movement is meant to capture closures of cities and roads, which may be independent of confining people to households. Seem reasonable @kararudolph ?

**Comment by scottyaz** [comment]
Added this --> ![image](https://user-images.githubusercontent.com/67367/77577874-dd6aa800-6ed7-11ea-91ea-41c3508d4bb2.png)

**Comment by kararudolph** [comment]
yes, makes sense
