### ISSUE TITLE
Military

### ISSUE THREAD

**Issue by forsbee** [HopkinsIDD/covid19-interventions#60]
Not so much an issue as a question-does using police to enforce measures count for the military question? Or is the goal to really get at whether military was called in, in addition to police?

**Comment by scottyaz** [comment]
I was thinking it was police **or** military for enforcing measures.Don't really care if military vs police or other.

**Comment by fjones2222** [comment]
@scottyaz  perhaps we should change the title of survey to "Military and Police Enforcement" rather than just "Military"

**Comment by scottyaz** [comment]
I thought I did. If not, go for it.

On 25 Mar 2020, at 22:58, Forrest K Jones wrote:

> @scottyaz  perhaps we should change the title of survey to "Military 
> and Police Enforcement" rather than just "Military"
>
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/HopkinsIDD/covid19-interventions/issues/60#issuecomment-604109438



andrew azman

**Comment by fjones2222** [comment]
I think the first text box was changed, but the title of the survey was not. Done
