### ISSUE TITLE
Change all "closed" answers to "fully_closed" or vise versa

### ISSUE THREAD

**Issue by sarahleavitt** [HopkinsIDD/covid19-interventions#66]
For harmony of answers it is better to have these consistent but doesn't matter which direction.
Currently closed borders has "full_closed" and nursing homes, offices, entertainment, stores, public transport, and public space have "closed"

**Comment by sarahleavitt** [comment]
This also might be relevant to open but haven't checked if the open wordings are consistent across interventions.

**Comment by scottyaz** [comment]
changed border options to be 'closed'
