### ISSUE TITLE
Survey Error for NJ, USA

### ISSUE THREAD

**Issue by sarahleavitt** [HopkinsIDD/covid19-interventions#69]
Even though I helped in the development, I still made a mistake...

For Leisure/entertainment/religious closures, the note should say that leisure and entertainment facilities were closed with no impact on religious venues (it should NOT say limited hours, that applied to stores). 

Whether it should be partially closed (currently correct) or fully closed (needs to be updated) depends on how religious venues are treated in this category.

**Comment by scottyaz** [comment]
Thanks! Will take care of this.

**Comment by sarahleavitt** [comment]
I am thinking it should also be changed to "closed" instead of "partially closed" doing research into more states (PA, FL) religious venues are actually usually distinct from this group, so I think that if everything is closed except religious venues, this category should still be denoted "closed"

**Comment by sarahleavitt** [comment]
This is record_id 130

**Comment by scottyaz** [comment]
@sarahleavitt the desc says "There is no restriction on religious venues but all leisure and entertainment venues have limited hours (5am-8pm)" so are they closed or just limited hours?

**Comment by sarahleavitt** [comment]
The corrections should be:
1. Status changed to closed instead of partially closed (everything in this category but religious venues should be closed).
2. Details should read: "There is no restriction on religious venues but all leisure and entertainment venues are closed".

If it is easier, I can just reenter this and then we can note to remove the original entry (not sure how we are doing this)

**Comment by scottyaz** [comment]
Done
