### ISSUE TITLE
Incorrect dates for records #396 and #478

### ISSUE THREAD

**Issue by sarahleavitt** [HopkinsIDD/covid19-interventions#82]
Intervention dates are for May and June of this year. Need to reach out to those who entered the data to find the correct month. (Note for these entries date_flag = TRUE)

**Comment by fjones2222** [comment]
slacked both individuals to remind them to fill out google form with corrections.

**Comment by sarahleavitt** [comment]
Fixed from google forms

**Comment by sarahleavitt** [comment]
Specifically I figured out #478 from the data in the rest of the border closures and #396 is in google forms.
