### ISSUE TITLE
Kentucky self-isolation

### ISSUE THREAD

**Issue by scottyaz** [HopkinsIDD/covid19-interventions#84]
First, the good news: I've entered all activities for Kentucky through 3/31. It's been a busy state! 

But: I started to enter a self-isolation then realized that it should be "other" because the population is just state residents returning to the state. They are not "suspected (symptomatic) cases". I entered an "Other" action. Please remove
Quarantine & self-isolation
March 30
Code ARARWEF7

**Comment by scottyaz** [comment]
Hi, I started to enter a restriction on long-term care facilities, but the restriction was for "senior centers," which are places for healthy elderly people to gather during the day, not a medical facility. Please delete it.
March 13 2020
Code 838XPFMD

**Comment by fjones2222** [comment]
@scottyaz I cannot find any records for  Nursing Home/Long-Term Care Closures for record 84
