### ISSUE TITLE
get_long_data() not reading in duration correctly.

### ISSUE THREAD

**Issue by sarahleavitt** [HopkinsIDD/covid19-interventions#90]
> dataL_cleanL <- get_long_data()
Parsed with column specification:
cols(
  .default = col_character(),
  record_id = col_double(),
  geography_and_intro_timestamp = col_datetime(format = ""),
  admin_1_unit_and_updates_timestamp = col_datetime(format = ""),
  timestamp = col_datetime(format = ""),
  t_original = col_date(format = ""),
  size = col_double(),
  duration = col_logical(),
  date_flag = col_logical(),
  date_error = col_logical(),
  t = col_date(format = "")
)
See spec(...) for full column specifications.
Warning: 16 parsing failures.
 row      col           expected actual                                  file
1180 duration 1/0/T/F/TRUE/FALSE     14 'generated_data/survey_data_long.csv'
1249 duration 1/0/T/F/TRUE/FALSE     14 'generated_data/survey_data_long.csv'
1287 duration 1/0/T/F/TRUE/FALSE     14 'generated_data/survey_data_long.csv'
1288 duration 1/0/T/F/TRUE/FALSE     14 'generated_data/survey_data_long.csv'
1298 duration 1/0/T/F/TRUE/FALSE     14 'generated_data/survey_data_long.csv'
.... ........ .................. ...... .....................................
See problems(...) for more details.

**Comment by sarahleavitt** [comment]
We could fix this by specifying all column types but that isn't robust to changing columns. I am not sure if there is another solution. I haven't worked much with read_csv()

**Comment by scottyaz** [comment]
With `read_csv()` you don't have to specify all. Any left unspecified it will guess and it usually does a pretty good job (except the desired behaviour is to assume logical when there is a ton of missing data).
