### ISSUE TITLE
Entries with unknown status missing dates/source documents

### ISSUE THREAD

**Issue by sarahleavitt** [HopkinsIDD/covid19-interventions#91]
The reason some entries are missing dates or source documents is that the status was chosen to be "unknown". This removes the requirement for these fields. The only exception is one office_closures entry because that date was accidentally not made required (this has a separate issue #89). Here is a csv with all of the entries missing date/source documents because of this problem (23 total) to be addressed in some fashion.

**Comment by fjones2222** [comment]
@scottyaz would it be useful to remove all unknown fields? I could go through and do this?

**Comment by scottyaz** [comment]
We should do it with the @HIDEOPTIONS action tag.

**Comment by scottyaz** [comment]
I mean @HIDECHOICE

**Comment by fjones2222** [comment]
I've hid the unknowns for all variables in the database. We can always unhide them at a later time.

[hideunknowns.xlsx](https://github.com/HopkinsIDD/covid19-interventions/files/4439846/hideunknowns.xlsx)

**Comment by fjones2222** [comment]
* for all status variables. See the attached excel file.

**Comment by sarahleavitt** [comment]
This shouldn't be closed yet. We still have to deal with the unknowns that were already entered. Do we contact those who entered them, try to figure out the dates ourselves, or remove the entries.

**Comment by sarahleavitt** [comment]
Added this to our audit report.
