### ISSUE TITLE
California, USA--Record ID 22

### ISSUE THREAD

**Issue by QLLZ** [HopkinsIDD/covid19-interventions#92]
_we made an error in one of our first entries. Can you please scratch this row so we can re-enter?_

**Record ID:** 22
**Intervention:** Nursing home/long-term care closures
**Date of update:** 2020-03-13

**Comment by fjones2222** [comment]
messaged catherine waiting to hear back

**Comment by fjones2222** [comment]
i have deleted this, she plans to reenter the data
