### ISSUE TITLE
Peru-Border Closures

### ISSUE THREAD

**Issue by AntiportaD** [HopkinsIDD/covid19-interventions#93]
Made a mistake uploading an erroneous source. 

It should have been the supreme decrete 044-2020-PCM instead of the 045-2020-PCM.

Need to change link and the file.

Link to the correct source is: 
[https://cdn.www.gob.pe/uploads/document/file/566448/DS044-PCM_1864948-2.pdf](url)

**Comment by scottyaz** [comment]
Done
