### ISSUE TITLE
Alabama---all records related to school closures

### ISSUE THREAD

**Issue by QLLZ** [HopkinsIDD/covid19-interventions#95]
_If it wouldn't be too much trouble, could you delete just the sub-surveys for School Closures for Alabama? That way I only have to re-do the entries for school closures._

**Comment by scottyaz** [comment]
@QLLZ - I see 4 entries for this. Should we delete all or all but the last?

**Comment by scottyaz** [comment]
- deleted 197 school data
- deleted 201 school data

**Comment by sarahleavitt** [comment]
Should be fixed, only school data is for record 210
